// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function VerifyAndDecodeJWT(arg1, arg2) {
  return window['go']['app']['App']['VerifyAndDecodeJWT'](arg1, arg2);
}
