// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {app} from '../models';

export function Startup(arg1:context.Context):Promise<void>;

export function VerifyAndDecodeJWT(arg1:string,arg2:Array<number>):Promise<app.JWTResult>;
